name: Publish Docker dev image

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/gutenberg
          manual-tag: dev
          latest-on-tag: false
          restrict-to: openzim/gutenberg
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
          repo_description: auto
          repo_overview: auto
