name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  build_python:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Ensure we can build Python targets
        run: |
          pip install -U pip build
          python3 -m build --sdist --wheel
